[project]
name = "wiki-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.26.0",
    "ruff>=0.15.2",
    "wikipedia>=1.4.0",
]
